site_name: AFiD-MuRPhFi Documentation
site_url: https://chowland.github.io/AFiD-MuRPhFi/
repo_url: https://github.com/chowland/AFiD-MuRPhFi
site_author: Chris Howland
markdown_extensions:
    - tables
    - markdown_katex:
        no_inline_svg: True
        insert_fonts_css: True
        macro-file: docs/macros.tex
theme: readthedocs
nav:
    - 'index.md'
    - Usage:
        - 'prerequisites.md'
        - 'inputs.md'
        - 'outputs.md'
        - 'pluto.md'
        - 'jupyter.md'
        - 'paraview.md'
    - Examples:
        - 'examples/rbc.md'
        - 'examples/ddc.md'
        - 'examples/freezing.md'
        - 'examples/melting_rbc.md'
    - 'Benchmarking and validation':
        - 'compilers.md'
        - 'convergence.md'
        - 'phasefield_validation.md'
    - 'Technical Details':
        - 'equations.md'
        - 'numerics.md'
        - 'buoyancy.md'
        - 'interpolation.md'
        - 'stretched_grids.md'