site_name: AFiD-MuRPhFi Documentation
site_url: https://chowland.github.io/AFiD-MuRPhFi/
repo_name: chowland/AFiD-MuRPhFi
repo_url: https://github.com/chowland/AFiD-MuRPhFi
site_author: Chris Howland
markdown_extensions:
    - tables
    - pymdownx.arithmatex:
        generic: true
    - attr_list
extra_css:
    - https://cdn.jsdelivr.net/npm/katex@0.13.13/dist/katex.min.css
extra_javascript:
    - javascripts/config.js
    - https://cdn.jsdelivr.net/npm/katex@0.13.13/dist/katex.min.js
theme:
    name: material
    palette:
        primary: deep orange
    font: false
    icon:
        logo: fontawesome/solid/wind
        repo: fontawesome/brands/github
    favicon: assets/favicon.png
nav:
    - 'index.md'
    - Usage:
        - 'prerequisites.md'
        - 'inputs.md'
        - 'outputs.md'
        - 'pluto.md'
        - 'jupyter.md'
        - 'paraview.md'
    - Examples:
        - 'examples/rbc.md'
        - 'examples/ddc.md'
        - 'examples/stefan.md'
        - 'examples/coupled_flows.md'
    - 'Benchmarking and validation':
        - 'compilers.md'
        - 'convergence.md'
        - 'phasefield_validation.md'
    - 'Technical Details':
        - 'equations.md'
        - 'numerics.md'
        - 'buoyancy.md'
        - 'interpolation.md'
        - 'stretched_grids.md'