# This workflow will do a clean install of the dependencies,
# and build the source code of AFiD

name: AFiD CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Install GFortran # NB gfortran and build-essential already on VM
      #   run: |
      #     sudo apt-get install build-essential gfortran

      - name: Install BLAS and LAPACK
        run: |
          sudo apt-get update
          sudo apt-get install libblas-dev liblapack-dev

      - name: Install Parallel HDF5
        run: sudo apt-get install libhdf5-openmpi-dev

      - name: Install FFTW library
        run: sudo apt-get install libfftw3-dev

      - name: Build AFiD
        run: make