# This workflow will build and deploy the documentation
# using MkDocs

name: Deploy documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - run: pip install mkdocs markdown-katex

      - run: mkdocs gh-deploy --force